### ISSUE TITLE
glGenBuffers invalid operation when adding measurement points on low mem GPU

### ISSUE THREAD

**Issue by samtygier-stfc** [ISISNeutronMuon/SScanSS-2#41]
* **This issue is a** bug report

* **What is the current behaviour?**

During testing of #40 I found the following on low memory GPUs where the fallback rendering is used. An integrated intel and an old AMD. I get a crash when I try to insert measurement points after loading a volume.

* **If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

- Launch SScans with #40 2061ee8 on the low mem GPU
- Insert -> Sample -> Volume -> From TIFF FIles
- Load ammonite dataset
- Sscanss give the insufficient memory warning and loads fallback
- Insert -> Measurement points -> Graphical Selection
- Crash

```
2022-04-01 11:05:41,444 - MainThread -  root - ERROR - An unhandled exception occurred!
Traceback (most recent call last):
  File "/home/sam/git/SScanSS-2/sscanss/app/window/dock_manager.py", line 156, in showPickPointDialog
    self.__showDockHelper(PickPointDialog)
  File "/home/sam/git/SScanSS-2/sscanss/app/window/dock_manager.py", line 124, in __showDockHelper
    widget = widget_class(*_params, self.parent)
  File "/home/sam/git/SScanSS-2/sscanss/app/dialogs/insert.py", line 397, in __init__
    self.prepareMesh()
  File "/home/sam/git/SScanSS-2/sscanss/app/dialogs/insert.py", line 423, in prepareMesh
    self.setPlane(self.plane_combobox.currentText())
  File "/home/sam/git/SScanSS-2/sscanss/app/dialogs/insert.py", line 816, in setPlane
    self.initializePlane(plane_normal, self.mesh.bounding_box.center)
  File "/home/sam/git/SScanSS-2/sscanss/app/dialogs/insert.py", line 829, in initializePlane
    self.parent.scenes.drawPlane(self.plane, 2 * plane_size, 2 * plane_size)
  File "/home/sam/git/SScanSS-2/sscanss/core/scene/scene.py", line 315, in drawPlane
    self.sample_scene.addNode(Attributes.Plane, self.plane_entity.node())
  File "/home/sam/git/SScanSS-2/sscanss/core/scene/entity.py", line 367, in node
    node.buildVertexBuffer()
  File "/home/sam/git/SScanSS-2/sscanss/core/scene/node.py", line 61, in buildVertexBuffer
    self.buffer = VertexArray(self.vertices, self.indices, self.normals)
  File "/home/sam/git/SScanSS-2/sscanss/core/scene/shader.py", line 334, in __init__
    self.vertex_buffer = GL.glGenBuffers(1)
  File "/home/sam/miniconda3/envs/sscanss-dev/lib/python3.7/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
  File "/home/sam/miniconda3/envs/sscanss-dev/lib/python3.7/site-packages/OpenGL/wrapper.py", line 678, in wrapperCall
    raise err
  File "/home/sam/miniconda3/envs/sscanss-dev/lib/python3.7/site-packages/OpenGL/wrapper.py", line 671, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/home/sam/miniconda3/envs/sscanss-dev/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGenBuffers,
	pyArgs = (1, <object object at 0x7fb63a5a2ff0>),
	cArgs = (1, array([52], dtype=uint32)),
	cArguments = (1, array([52], dtype=uint32))
)

```

* **Please tell about the environment(s) affected:**
  
  - Version: #40 2061ee8 
  - Operating System: Ubuntu 20
  - Platform: i9-10885H, 64GB RAM, Intel UHD Graphics for 10th Gen Intel Processors
  - `GPU: Mesa Intel(R) UHD Graphics (CML GT2), Driver Version: 4.6 (Compatibility Profile) Mesa 21.2.6, PBO Support: True`

  
* **Other information (e.g. detailed explanation, screenshots, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc):**

**Comment by samtygier-stfc** [comment]
If I just load a subset of the ammonite data (e.g. just 100x1521x549), then I get the full volume rendering and the measurement point selection works.
